name: CPack

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest -b release-1.11.0

  - name: Configure example
    run: cmake -H. -B ${{github.workspace}}/build 

  - name: Build example
    run: cmake --build ${{github.workspace}}/build

  - name: Run tests
    run: build/check
    
  - name: Artifact
    uses: actions/upload-artifact@v4
    with:
     name: example
     path: build/example
