name: CPack

on:
 push:
  branches: [main]
 pull_request:
  branches: [main]

jobs: 
 build_Linux:

  runs-on: ubuntu-latest

  steps:
  - uses: actions/checkout@v4

  - name: putting gtest
    run: git clone https://github.com/google/googletest.git third-party/gtest

  - name: Configure example
    run: cmake ${{github.workspace}} -B ${{github.workspace}}/build

  - name: Build example
    run: cmake --build ${{github.workspace}}/build
  - name: Upload artifact
    uses: actions/upload-artifact@v2
    with:
     name: my-executable
     path: /home/runner/work/Rk/Rk/rk2
