name: Build and Test

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up CMake
      uses: lukka/get-cmake@v1

    - name: Configure and build
      run: |
        cmake -B build
        cmake --build build

    - name: Run tests
      run: |
        cd build
        ctest

    - name: Upload artifact
      uses: actions/upload-artifact@v2
      with:
        name: my-executable
        path: /home/runner/work/Rk/Rk/rk2
